name: Build and Push Docker Image on Model Change

on:
  push:
    paths:
      - 'vhm_center.pt'    # Only run workflow when model file changes
    branches:
      - main
  workflow_dispatch:  #  Add this to enable manual runs

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GH_PAT }}
            fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read and bump version
        id: versioning
        run: |
          VERSION=$(cat VERSION)
          NUM=${VERSION#v}
          NEXT_NUM=$((NUM + 1))
          NEXT_VERSION="v${NEXT_NUM}"
          echo "Current version: $VERSION"
          echo "Next version: $NEXT_VERSION"

          echo "$NEXT_VERSION" > VERSION
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Commit new version file
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add VERSION
          git commit -m "Bump version to $NEXT_VERSION" || echo "No changes"
          git push origin main

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with version tag
        run: |
          docker build -t remz01/llogbert-api:${{ env.NEXT_VERSION }} .
          docker tag remz01/llogbert-api:${{ env.NEXT_VERSION }} remz01/llogbert-api:latest

      - name: Push Docker images
        run: |
          docker push remz01/llogbert-api:${{ env.NEXT_VERSION }}
          docker push remz01/llogbert-api:latest
